name: Flarum Auto Publisher

on:
  schedule:
    - cron: '1 00 * * *'  # 台灣早上 08:00
    - cron: '2 04 * * *'   # 台灣中午 12:00
    - cron: '4 08 * * *'  # 台灣傍晚 16:00
    - cron: '4 12 * * *'  # 台灣晚上 20:00
    - cron: '3 16 * * *'  # 台灣凌晨 00:00
  workflow_dispatch: # 支持手動點擊執行測試

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 賦予寫入權限，以便推送 history.json
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests feedparser google-generativeai trafilatura

      - name: Run Bot
        env:
          SERVER_API_URL: ${{ secrets.SERVER_API_URL }}
          FLARUM_API_KEY: ${{ secrets.FLARUM_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          NVIDIA_API_KEY: ${{ secrets.NVIDIA_API_KEY }}
        run: python bot.py

      - name: Commit history
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add history.json
          git commit -m "Update post history [skip ci]" || exit 0
          git push
